# Config file for automatic testing at travis-ci.org
language: python
sudo: false
python:
  - '3.6'
  - '3.7'
# Command to install dependencies
install:
  - pip install pytest
# Command to run tests
script:
  - pytest
